# Generated by Django 5.1.3 on 2025-02-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sign-language', 'Sign Language'), ('deaf-history', 'Deaf History'), ('education', 'Education Materials')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
