# Generated by Django 5.1.3 on 2025-01-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(default=models.TextField(), max_length=500),
        ),
    ]
