# Generated by Django 5.1.3 on 2025-02-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_interpreterapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreterapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
