# Generated by Django 5.1.3 on 2025-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='long_description',
            field=models.TextField(default=True, max_length=500),
        ),
    ]
