# Generated by Django 5.1.3 on 2025-02-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_event_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
