# Generated by Django 5.1.3 on 2025-02-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_interpretation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreterapplication',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='interpreters/'),
        ),
    ]
