# Generated by Django 5.1.3 on 2025-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_interpreterapplication_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreterapplication',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interpreterapplication',
            name='county',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
