# Generated by Django 5.1.3 on 2025-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_communitygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='is_new',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
