# Generated by Django 5.1.3 on 2025-03-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_galleryimage_alter_event_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='long_description',
            field=models.TextField(default=True, max_length=1000),
        ),
    ]
