# Generated by Django 5.1.3 on 2025-03-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_remove_signdata_x_values_remove_signdata_y_values_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignData',
        ),
    ]
