# Generated by Django 5.1.3 on 2025-04-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_featuredservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredservice',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='featuredservice',
            name='link',
        ),
    ]
