# Generated by Django 5.1.3 on 2025-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_remove_featuredservice_icon_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro_text', models.TextField()),
                ('bullet_1', models.CharField(max_length=255)),
                ('bullet_2', models.CharField(max_length=255)),
                ('bullet_3', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about_images/')),
            ],
        ),
    ]
