# Generated by Django 5.1.3 on 2025-04-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_aboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='educational_resources/files/'),
        ),
        migrations.AlterField(
            model_name='educationalresource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='educational_resources/images/'),
        ),
    ]
